#+TITLE: TM1
#+AUTHOR: Cristian Romero Andrade, Chávez Magaña Manuel y Sánchez Bautista Alan Ulises
#+options: title:nil toc:nil

#+language: es

#+latex_header: \include{main_config}


#+latex: \input{../../portada.tex}
#+latex: \renewcommand{\thesection}{1.\arabic{section}}

* Mecánica cuántica y vida real
Generalmente la mecánica cuántica se le identifica una rama de la física
sumamente difícil de entender, uno llega a imaginar a científicos e ingenieros
creando máquinas sumamente gigantes para ver objetos indefinidamente pequeños.
La mecánica cuántica llega a ser compleja, pero se inició con las preguntas más
simples como ¿De qué color y por qué el color?

La mecánica cuántica no solo se basa en responder las preguntas existenciales de
los colores, sino para explicar la mayoría de las propiedades de los materiales.
¿Por qué algunos materiales son duros y otros blandos?, ¿por qué hay materiales que
reflejan luz?, ¿por qué hay materiales transparentes?, etc. de estas preguntas se
encargan otras ciencias como la química, y ramas derivadas de la física; la visión
de la mecánica cuántica se basa de aquellas ramas y de ellas esta comienza a
ensamblarse.

Si bien la mecánica cuántica, en materia, puede llegar a ser imprescindible para
el desarrolló de varios artilugios que hoy en día usamos, sin embargo se usan teoría
cuántica en la técnica para diseñar los dispositivos que ejecutan nuestras
computadoras y conexiones a redes externas.

Las ideas matemáticas de la informática y la información habían comenzado a tomar su
forma moderna en las décadas de 1930, 1940 y 1950. En la década de 1950, los teléfonos
y las comunicaciones por radio y televisión estaban bien establecidos, y se demostraron
las primeras computadoras electrónicas primitivas. El transistor y el circuito integrado
fueron los siguientes avances clave. Estos dispositivos hicieron que las computadoras
complejas y la conmutación y el procesamiento de información fueran prácticos. Estos
dispositivos se basaron en gran medida en la física mecánica cuántica de los materiales
cristalinos. A medida que intentamos reducir los transistores a tamaños cada vez más
pequeños, los efectos de la mecánica cuántica se vuelven progresivamente más
importantes. Extrapolar ingenuamente la tendencia histórica en miniaturización
conduciría a dispositivos del tamaño de moléculas pequeñas en las primeras décadas
del siglo XXI (\cite[pp. 1--4]{miller2014}).


* La mecánica cuántica como logro intelectual
Todas las nuevas teorías científicas tienen que tener las mismas respuestas que todas las
teorías anteriores, y a la vez explicar un fenómeno completamente nuevo para nosotros.

Si utilizamos modelos que han trabajado bien anteriormente para explicar casos complejos
como el comportamiento de un átomo, se pueden encontrar contradicciones y errores.
Para poder resolver problemas que tengan que ver con luz y estructura de la materia, los
modelos convencionales se quedan cortos, por lo que se tuvieron que crear nuevas reglas que
desafían teorías anteriores y que pueden llegar a ser bastante bizarras.

La mecánica cuántica es una ciencia tan nueva y abstracta que aún no la logramos comprender
del todo. Podemos definir que una partícula siempre está en estado de superposición, esto
implica que puede estar definitivamente a la derecha o a la izquierda, pero no es hasta que
la medimos que sabemos su ubicación exacta, como si fuera un truco de magia, conocido como
el colapso de la función de onda.

Schrodinger explica la superposición a través de un ejemplo relativamente simple. Encierra
a su gato en una caja con un mecanismo letal el cual solo se activa por el resultado, por
ejemplo, de la degradación de un material radiactivo. No sabemos si el gato está vivo o
muerto hasta que la caja sea abierta, lo que la mecánica cuántica sugiere es que el gato se
encuentre en un estado de superposición entre la vida y la muerte.

La mecánica cuántica nos permite predecir un promedio de la posición de un electrón y del
tiempo de vida de un núcleo, pero no nos daría la posición exacta ni el tiempo.

No podemos predecir el estado de las cosas, hay cierta aleatoriedad en nuestras vidas, la
única forma que creemos que podemos predecir un sucesos es conociendo su posición inicial,
sin embargo, esta información no es existente.

Einstein creía que la mecánica cuántica estaba incompleta, que hacían falta variables
escondidas que al ser descubiertas resolverían nuestros problemas de aleatoriedad.

A pesar de lo absurdo, sin sentidos, y contradicciones de la mecánica cuántica, esta
funciona, de hecho nunca se equivoca. Han habido mediciones sin experimentos y estas casi
siempre son correctas a pesar de sus contradicciones. A pesar de ser tan inconvencional es
tan exacta.

 La historia de la mecánica cuántica está comenzando, aún falta por descubrir partículas
 fundamentales y sus funciones en el universo. Muchos científicos siguen descubriendo usos
 de la mecánica cuántica, como computadoras cuánticas y transmisión de información (\cite[pp.~4--6]{miller2014}).


* Utilizando la mecánica cuántica
En este punto el pobre estudiante tal vez esté cerca de rendirse en
desesperación ¿cómo puede uno entender una teoría bizarra? y si uno
puede entender esto ¿cómo puede uno usar estas cosas?, aquí están las
buenas noticias: ya sea que nosotros entendamos cosas de mecánica
cuántica o no, y ya sea si hay más cosas por descubrir sobre cómo
trabajar con esto, la mecánica cuántica es sorprendentemente fácil de
usar.

La principal dificultad que tienen los estudiantes principiantes tiene
que ver con saber que nociones de la mecánica clásica deben descartar, y
qué nuevas nociones tienen que usar para reemplazarlas.

El estudiante debe esperar pasar algún tiempo en incredulidad y
conflicto,con lo que es acertado en la mecánica cuántica esto es
enteramente normal.

Nuestro uso de los principios de mecánica cuántica en aplicaciones
tangibles tales como electrónicos o dispositivos ópticos y sistemas, la
apariencia aparentemente bizarra puede convertirse en algo común y
rutinario.

Entender esto le da al estudiante la oportunidad para aplicar los
conocimientos en el camino que otros no pueden comenzar a comprender
(\cite[pp.~6--8]{miller2014}).



#+latex: \addcontentsline{toc}{section}{Referencias}
#+latex: \printbibliography{}
